"""waifu model

Revision ID: 7478903d6aa4
Revises: 7798c98db03d
Create Date: 2025-06-21 06:25:17.819508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7478903d6aa4'
down_revision: Union[str, Sequence[str], None] = '7798c98db03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waifus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('waifu_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'waifus', ['waifu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'waifu_id')
    op.drop_table('waifus')
    # ### end Alembic commands ###
